apiVersion: v1
kind: Service
metadata:
  labels:
    app: prom-blackbox-exporter
  name: prom-blackbox-exporter
spec:
  ports:
  - name: metrics
    port: 9115
    targetPort: 9115
    protocol: TCP
  selector:
    app: prom-blackbox-exporter
