apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "Prometheus"
metadata:
  name: prometheus-k8s
  labels:
    prometheus: k8s
spec:
  retention: "48h"
  resources:
    requests:
      memory: 200Mi
      cpu: 250m
  storage:
    selector:
      matchLabels:
        app: k8s-prom
    resources:
      requests:
        storage: 50Gi
