apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: k8s
  labels:
    prometheus: k8s
spec:
  replicas: 1
  retention: "2h"
  serviceMonitorSelector:
    matchExpression:
    - {key: k8s-apps, operator: Exists}
  ruleSelector:
    matchLabels:
      role: prometheus-rulefiles
      prometheus: k8s
  resources:
    requests:
      memory: 800Mi
    limits:
      memory: 1Gi
  storage:
    selector:
      matchLabels:
        app: k8s-prom
    resources:
      requests:
        storage: 50Gi
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-k8s
      port: web
