apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    operator: prometheus
  name: prometheus-operator
spec:
  replicas: 1
  template:
    metadata:
      labels:
        operator: prometheus
    spec:
      containers:
      - name: prometheus-operator
        image: quay.io/coreos/prometheus-operator:v0.13.0
        args:
        - -kubelet-service=kube-system/kubelet
        env:
        - name: GLOG_v
          value: "5"
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
