apiVersion: v1
kind: Service
metadata:
  name: synapse-backregister
  labels:
    app: synapse-backregister
spec:
  type: NodePort
  selector:
    app: synapse-backregister
  ports:
  - name: http
    port: 80
    targetPort: 8000
