dependencies:
  - name: postgresql
    version: 0.6.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: kube-lego
    version: 0.1.8
    repository: https://kubernetes-charts.storage.googleapis.com/
