apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wobscale-matrix-pw-reset
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - wobscale.chat
    secretName: wobscale-chat-cert-2
  rules:
  - host: wobscale.chat
    http:
      paths:
      - path: "/password/reset"
        backend:
          serviceName: synapse-password-reset
          servicePort: 80
