apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "Prometheus"
metadata:
  name: wob-prom
  labels:
    prometheus: wob
spec:
  retention: "48h"
  storage:
    selector:
      matchLabels:
        app: wob-prom
    resources:
      requests:
        storage: 50Gi
