apiVersion: v1
kind: Service
metadata:
  labels:
    app: wob-prom
    prometheus: wob-prom
  name: wob-prom
spec:
  ports:
  - name: metrics
    port: 9090
    protocol: TCP
  selector:
    prometheus: wob-prom
