apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wobscale-paypi-server
  labels:
    name: "wobscale-paypi-server"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: wobscale-paypi-server
        app: wobscale-paypi-server
    spec:
      containers:
      - name: s
        image: wobscale/payments-server:6658e07
        env:
        - name: CORS_ALLOW_ORIGIN
          value: "https://pay.wobscale.website"
        - name: GITHUB_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: paypi-secrets-prod
              key: GITHUB_CLIENT_ID
        - name: GITHUB_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: paypi-secrets-prod
              key: GITHUB_SECRET_KEY
        - name: STRIPE_API_KEY
          valueFrom:
            secretKeyRef:
              name: paypi-secrets-prod
              key: STRIPE_API_KEY
        resources:
          limits:
            memory: 200Mi
          requests:
            memory: 100Mi
        ports:
          - name: http
            containerPort: 8080
