apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wobscale-paypi-client
spec:
  tls:
  - hosts:
    - pay.wobscale.website
    secretName: pay-wobscale-website-cert-2
  rules:
  - host: pay.wobscale.website
    http:
      paths:
      - path: "/"
        backend:
          serviceName: pay-wobscale-website
          servicePort: 80
