apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "euircbot"
  labels:
    name: "euircbot"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: euircbot
    spec:
      containers:
      - name: euircbot
        image: "quay.io/euank/euircbot:latest"
        command: ["node", "--max_old_space_size=400", "index.js"]
        resources:
          requests:
            memory: 600Mi
          limits:
            # TODO, lower this number once memory leaks are plugged
            memory: 800Mi
        volumeMounts:
        - name: module-config
          mountPath: "/usr/src/app/conf/"
        - name: data
          mountPath: "/usr/src/app/data/"
        - name: config
          mountPath: "/usr/src/app/config.json"
          subPath: config.json # *sigh* TODO make this not need subpath
      volumes:
        - name: module-config
          configMap:
            name: "euircbot-modules"
        - name: config
          configMap:
            name: "euircbot"
        - name: data
        {{- if .Values.euircbot.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: "euircbot"
        {{- else }}
          emptyDir: {}
        {{- end -}}
