apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "euircbot"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: "euircbot-modules"
data:
  blerg.json: |-
    {
      "username": {{ .Values.euircbot.moduleConfig.blerg.username | quote }},
      "password": {{ .Values.euircbot.moduleConfig.blerg.password | quote }}
    }
  dumbcommand.json: |-
    {
      "allow_commands": {{ .Values.euircbot.moduleConfig.dumbcommand.allowCommands }}
    }
  google.json: |-
    {
      "apiKey": {{ .Values.euircbot.moduleConfig.google.apiKey | quote }}
    }
  googleimgs.json: |-
    {
      "cseID": {{ .Values.euircbot.moduleConfig.googleImgs.cseID | quote }}
    }
  qdb.json: |-
    {
      "source": {{ .Values.euircbot.moduleConfig.qdb.source | quote }},
      "baseUrl": {{ .Values.euircbot.moduleConfig.qdb.baseUrl | quote }}
    }
  twitter.json: |-
    {
      "consumer_key": {{ .Values.euircbot.moduleConfig.twitter.consumerKey | quote }},
      "consumer_secret": {{ .Values.euircbot.moduleConfig.twitter.consumerSecret | quote }},
      "access_token": {{ .Values.euircbot.moduleConfig.twitter.accessToken | quote }},
      "access_token_secret": {{ .Values.euircbot.moduleConfig.twitter.accessTokenSecret | quote }},
      "baseUrl": {{ .Values.euircbot.moduleConfig.twitter.baseUrl | quote }}
    }
  weather.json: |-
    {
      "wunderground_key": {{ .Values.euircbot.moduleConfig.weather.wundergroundKey | quote }},
      "google_key": {{ .Values.euircbot.moduleConfig.google.apiKey | quote }}
    }
  wolfram.json: |-
    {
      "appid": {{ .Values.euircbot.moduleConfig.wolfram.appId | quote }}
    }
  wotd.json: |-
    {
      "wotd_key": {{ .Values.euircbot.moduleConfig.wotd.wotdKey | quote }}
    }
  cmdio.json: |-
    {
      "accessToken": {{ .Values.euircbot.moduleConfig.cmdio.accessToken | quote }}
    }
