apiVersion: v1
kind: Service
metadata:
  labels:
    app: prom-irc-exporter
  name: prom-irc-exporter
spec:
  ports:
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: prom-irc-exporter
