apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prom-irc-exporter
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: prom-irc-exporter
    spec:
      containers:
      - name: prom-irc-exporter
        image: wobscale/prometheus-irc-exporter:8eb3144
        ports:
        - name: metrics
          containerPort: 8080
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 60Mi
            cpu: 200m
