apiVersion: v1
kind: Secret
metadata:
    name: synapse-pg-user
type: Opaque
data:
    user: {{ .Values.matrix.synapse.db.user | b64enc | quote }}
    password: {{ .Values.matrix.synapse.db.pass | b64enc | quote }} 
