apiVersion: v1
kind: Service
metadata:
  name: syncplay-server
  labels:
    app: syncplay-server
spec:
  type: NodePort
  selector:
    app: syncplay-server
  ports:
  - name: syncplay
    port: 8999
    targetPort: 8999

