apiVersion: "monitoring.coreos.com/v1"
kind: "Prometheus"
metadata:
  name: wob-prom
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    prometheus: wob-prom
spec:
  retention: "48h"
  resources:
    requests:
      memory: 500Mi
  storage:
    volumeClaimTemplate:
      metadata:
        labels:
          app: wob-prob
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 50Gi
        selector:
          matchLabels:
            app: wob-prom
