apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "jenkins-master"
  labels:
    app: "jenkins-master"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jenkins-master
    spec:
      containers:
      - name: jenkins-master
        # jenkins/jenkins:lts @ 2018-05-31
        image: "jenkins/jenkins@sha256:7f060c45fef3e0e598ba58a84b06c7b687cd25f59930137d9e03b40fb1ede2fc"
        env:
        - name: JAVA_OPTS
          value: "-Xmx700m"
        resources:
          requests:
            memory: 800Mi
          limits:
            memory: 1200Mi
        volumeMounts:
        - name: data
          mountPath: "/var/jenkins_home"
      volumes:
        - name: data
          nfs:
            server: 192.168.131.1
            path: "/mnt/raid1/nfs/k8s/jenkins/"
