apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-ingress-controller
  labels:
    k8s-app: nginx-ingress-lb
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 1.1.0
spec:
  selector:
    matchLabels:
      k8s-app: nginx-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: nginx-ingress-lb
        name: nginx-ingress-lb
    spec:
      serviceAccountName: nginx-ingress-serviceaccount
      hostNetwork: true
      nodeSelector:
        ingress: "true"
      terminationGracePeriodSeconds: 60
      containers:
      - image:  quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.9.0
        name: nginx-ingress-lb
        imagePullPolicy: Always
        ## TODO these are broken on my dep because of being hostnetworking
        ## readinessProbe:
        ##   httpGet:
        ##     path: /healthz
        ##     port: 10254
        ##     scheme: HTTP
        ## livenessProbe:
        ##   httpGet:
        ##     path: /healthz
        ##     port: 10254
        ##     scheme: HTTP
        ##   initialDelaySeconds: 10
        ##   timeoutSeconds: 1
        # use downward API
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        - containerPort: 8999
          hostPort: 8999
        args:
        - /nginx-ingress-controller
        - --default-backend-service=$(POD_NAMESPACE)/default-http-backend
        - --configmap=$(POD_NAMESPACE)/nginx-load-balancer-conf
        - --tcp-services-configmap=$(POD_NAMESPACE)/nginx-tcp-ingress-configmap
        - --annotations-prefix=ingress.kubernetes.io
        volumeMounts:
        - mountPath: /etc/nginx-ssl/dhparam
          name: ingress-dhparam
      volumes:
      - name: ingress-dhparam
        secret:
          secretName: ingress-dhparam
