apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon
  labels:
    app: mastodon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mastodon
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: mastodon
    spec:
      containers:
      - name: mastodon
        image: "wobscale/mastodon:v3.5.1-6-g22efeee80"
        command: ["sh", "-c", "cp /config/favicon.ico /mastodon/public/favicon.ico && exec bundle exec puma -C config/puma.rb"]
        ports:
        - containerPort: 3000
        env:
        - name: RAILS_ENV
          value: production
        - name: PORT
          value: "3000"
{{ include "environment" . | indent 8 }}
        livenessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
        readinessProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 15
        resources:
          limits:
            memory: 2500Mi
          requests:
            memory: 1600Mi
        volumeMounts:
        - name: system
          mountPath: /mastodon/public/system
        - name: site-config
          mountPath: /config/
      volumes:
      - name: system
        nfs:
          server: 192.168.131.1
          path: /mnt/raid1/nfs/k8s/mastodon/system
      - name: site-config
        nfs:
          server: 192.168.131.1
          path: /mnt/raid1/nfs/k8s/mastodon/config/
