apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mastodon-ing
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20M"
    ingress.kubernetes.io/proxy-body-size: "20M"
spec:
  tls:
  - hosts:
    - wobscale.social
    secretName: wobscale-social-cert-2
  rules:
  - host: wobscale.social
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: mastodon
            port:
              number: 80
      - path: "/api/v1/streaming"
        pathType: Prefix
        backend:
          service:
            name: mastodon-streaming
            port:
              number: 4000
