apiVersion: v1
kind: Secret
metadata:
    name: mastodon-secrets
type: Opaque
data:
  otpSecret: {{ .Values.mastodon.otpSecret | b64enc | quote }}
  secretKeyBase: {{ .Values.mastodon.secretKeyBase | b64enc | quote }}
  paperclipSecret: {{ .Values.mastodon.paperclipSecret | b64enc | quote }}
