apiVersion: v1
kind: Secret
metadata:
    name: mastodon-postgres-user
type: Opaque
data:
    user: {{ .Values.mastodon.db.user | b64enc | quote }}
    password: {{ .Values.mastodon.db.pass | b64enc | quote }} 
