apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mastodon-sidekiq
  labels:
    app: mastodon-sidekiq
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: mastodon-sidekiq
    spec:
      containers:
      - name: mastodon-sidekiq
        image: wobscale/mastodon:v2.7.1-6-gff91da9e2
        args: ["bundle", "exec", "sidekiq", "-q", "default", "-q", "mailers", "-q", "pull", "-q", "push"]
        ports:
        - containerPort: 4000
        env:
{{ include "environment" . | indent 8 }}
        volumeMounts:
        - name: system
          mountPath: /mastodon/public/system
      volumes:
      - name: system
        nfs:
          server: 192.168.131.1
          path: /mnt/raid1/nfs/k8s/mastodon/system
