apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mastodon-streaming
  labels:
    app: mastodon-streaming
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: mastodon-streaming
    spec:
      containers:
      - name: mastodon-streaming
        image: wobscale/mastodon:v2.6.1-6-g311bcb0d0
        command: ["yarn", "start"]
        ports:
        - containerPort: 4000
        env:
{{ include "environment" . | indent 8 }}
