apiVersion: v1
kind: ConfigMap
metadata:
  name: matrix-irc-config
data:
  registration.yaml: |-
    id: {{.Values.service.id | quote }}
    hs_token: {{.Values.service.hs_token | quote }}
    as_token: {{.Values.service.as_token | quote }}
    rate_limited: false
    url: 'http://matrix-irc:9999'
    sender_localpart: irc
    namespaces:
      users:
        - exclusive: true
          regex: '@irc\.wobscale\.website_.*:wobscale\.chat'
      aliases:
        - exclusive: true
          regex: '#irc_.*:wobscale\.chat'
      rooms:
{{- range $channel, $roomIds := .Values.service.mappings -}}
{{- range $roomId := $roomIds }}
        - exclusive: false
          regex: {{ $roomId | quote }}
{{- end -}}
{{- end }}

  config.yaml: |-
    homeserver:
      url: "https://wobscale.chat"
      domain: "wobscale.chat"
    ircService:
      databaseUri: "nedb:///data"
      servers:
        irc.wobscale.website:
          port: 6697
          ssl: true
          ircClients:
            allowNickChanges: true
          botConfig:
            nick: "matrix[irc]"
          dynamicChannels:
            enabled: true
            published: false
            createAlias: true
            joinRule: public
            aliasTemplate: "#irc_$CHANNEL"
          mappings:
{{ .Values.service.mappings | toYaml | indent 12 }}
