apiVersion: v1
kind: Service
metadata:
  name: matrix-irc
  labels:
    app: matrix-irc
spec:
  type: NodePort
  selector:
    app: matrix-irc
  ports:
  - name: p
    port: 9999
    targetPort: 9999
