apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wobscale-matrix
  annotations:
    stable.k8s.psg.io/kcm.enabled: "true"
    stable.k8s.psg.io/kcm.provider: "cloudflare"
    stable.k8s.psg.io/kcm.email: "admin@wobscale.website"
    ingress.kubernetes.io/proxy-body-size: "50M"
spec:
  tls:
  - hosts:
    - wobscale.chat
    secretName: wobscale.chat
  rules:
  - host: wobscale.chat
    http:
      paths:
      - path: "/"
        backend:
          serviceName: synapse
          servicePort: 80
      - path: "/{{ .Values.matrix.registration.secretPath }}"
        backend:
          serviceName: synapse-backregister
          servicePort: 80
