apiVersion: v1
kind: Service
metadata:
  name: synapse
  labels:
    app: synapse
spec:
  type: NodePort
  selector:
    app: synapse
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: http2
    port: 8448
    targetPort: 8448
