apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: synapse
    name: synapse
  name: synapse
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synapse
      name: synapse
  template:
    metadata:
      annotations:
        app: synapse
      labels:
        app: synapse
        name: synapse
    spec:
      containers:
      - name: synapse
        image: euank/synapse:1.34.0-1
        resources:
          requests:
            memory: 1500Mi
        volumeMounts:
        - name: data
          mountPath: /data/
        - name: secret
          mountPath: /secret/
        - name: conf
          mountPath: /conf/
        - name: certs
          mountPath: /certs/
        - name: irc-svc
          mountPath: /matrix-irc/
      volumes:
      - name: data
        nfs:
          path: {{ .Values.matrix.synapse.nfsDataPath }}
          server: {{ .Values.matrix.synapse.nfsServer }}
      - name: secret
        secret:
          secretName: synapse-secret
      - name: conf
        configMap:
          name: synapse-config
      - name: certs
        secret:
          secretName: wobscale-chat-cert-2
      - name: irc-svc
        configMap:
          name: matrix-irc-config
          items:
          - key: registration.yaml
            path: registration.yaml
