apiVersion: v1
kind: ConfigMap
metadata:
  name: synapse-logconfig
data:
  log.config: |-
    version: 1

    formatters:
      precise:
        format: '%(asctime)s - %(name)s - %(lineno)d - %(levelname)s - %(request)s- %(message)s'

    filters:
      context:
        (): synapse.util.logcontext.LoggingContextFilter
        request: ""

    handlers:
      file:
        class: logging.handlers.RotatingFileHandler
        formatter: precise
        filename: /var/log/synapse/homeserver.log
        maxBytes: 104857600
        backupCount: 10
        filters: [context]
        level: WARN
      console:
        class: logging.StreamHandler
        formatter: precise

    loggers:
      synapse:
        level: WARN

        synapse.storage.SQL:
          level: WARN

    root:
      level: WARN
      handlers: [file, console]

