apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-web
  labels:
    app: {{ template "fullname" . }}-web-deployment
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ template "fullname" . }}-web
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        args: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
        env:
        - name: PAPERCLIP_SECRET
          {{- if .Values.paperclipSecret }}
          value: {{ .Values.paperclipSecret }}
          {{- else }}
          value: {{ randAlphaNum 32 | b64enc | quote }}
          {{- end }}
        - name: SECRET_KEY_BASE
          {{- if .Values.secretKeyBase  }}
          value: {{ .Values.secretKeyBase  }}
          {{- else }}
          value: {{ randAlphaNum 32 | b64enc | quote }}
          {{- end }}
        - name: OTP_SECRET
          {{- if .Values.OTPSecret }}
          value: {{ .Values.OTPSecret }}
          {{- else }}
          value: {{ randAlphaNum 32 | b64enc | quote }}
          {{- end }}
#        - name: REDIS_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: {{ template "fullname" . }}
#              key: redis-password
        ports:
        - name: web
          containerPort: 3000
#        livenessProbe:
#          exec:
#            command:
#            - redis-cli
#            - ping
#          initialDelaySeconds: 30
#          timeoutSeconds: 5
#        readinessProbe:
#          exec:
#            command:
#            - redis-cli
#            - ping
#          initialDelaySeconds: 5
#          timeoutSeconds: 1
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: web-assets
          mountPath: /mastodon/public/assets
        - name: web-system
          mountPath: /mastodon/public/system
      volumes:
      - name: web-assets
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingAssetsClaim | default (include "fullname" .) }}-web-assets
      - name: web-system
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingSystemClaim | default (include "fullname" .) }}-web-system

