apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-streaming
  labels:
    app: {{ template "fullname" . }}-streaming-deployment
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-streaming
    spec:
      containers:
      - name: {{ template "fullname" . }}-streaming
        image: {{ .Values.image | quote }}
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        args: ["npm", "run", "start"]
        env:
{{ include "mastodon.env_discovery" . | indent 8 }}
{{ include "mastodon.env_secrets" . | indent 8 }}
        ports:
        - name: streaming
          containerPort: 4000
        livenessProbe:
             exec:
               command:
               - echo
               - "this is not a very good healthcheck"
             initialDelaySeconds: 60
             periodSeconds: 3
        readinessProbe:
             exec:
               command:
               - echo
               - "this is not a very good healthcheck"
             initialDelaySeconds: 3
             periodSeconds: 3
        resources:
{{ toYaml .Values.resources | indent 10 }}
