apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-web
  labels:
    app: {{ template "fullname" . }}-web
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}-web
    spec:
      containers:
      - name: {{ template "fullname" . }}-web
        image: {{ .Values.image | quote }}
        imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
        args: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
        env:
        - name: LOCAL_DOMAIN
          value: {{ .Values.localDomain | quote }}
        - name: LOCAL_HTTPS
          value: {{ default false .Values.localHTTPS | quote }}
{{ include "mastodon.env_discovery" . | indent 8 }}
{{ include "mastodon.env_secrets" . | indent 8 }}
        ports:
        - name: web
          containerPort: 3000
        livenessProbe:
             httpGet:
               path: /about
               port: web
             initialDelaySeconds: 60
             periodSeconds: 3
        readinessProbe:
             httpGet:
               path: /about
               port: web
             initialDelaySeconds: 3
             periodSeconds: 3
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: web-assets
          mountPath: /mastodon/public/assets
        - name: web-system
          mountPath: /mastodon/public/system
      volumes:
      - name: web-assets
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingAssetsClaim | default (include "fullname" .) }}-web-assets
      - name: web-system
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingSystemClaim | default (include "fullname" .) }}-web-system

