apiVersion: v1
kind: Service
metadata:
  labels:
    app: kube-cert-manager-ek
  name: kube-cert-manager-ek
spec:
  type: NodePort
  selector:
    app: kube-cert-manager-ek
  ports:
  - name: http
    port: 8080
    targetPort: 8080
